In [1]:
import connection as cn
import pandas as pd

from sqlalchemy import create_engine
from datetime import datetime

In [2]:
def highlight_odd_rows(row):
    # Check if the row index is odd
    if row.to  == 'central' and row.trailer_registration == '722735':
        # Return a list of style strings for each cell in the row
        return ['background-color: #595959'] * len(row)
    elif row.to == 'central' and row.trailer_registration == 'outsource_petch':
        return  ['background-color: #E65100'] * len(row)
    elif row.to == 'central' and row.trailer_registration == 'outsource_ta':
        return  ['background-color: #B83E3E'] * len(row)
    else:
        # Return an empty list for even rows (no styling)
        return [''] * len(row)


def highlight_rows(row):
    # Check if the row index is odd
    if row.to  == 'central' and row.froms == 'south':
        # Return a list of style strings for each cell in the row
        return ['background-color: #595959'] * len(row)
    
    elif row.to == 'chiangmai' and row.froms == 'central' : 
        return  ['background-color: #B83E3E'] * len(row)
    
    elif row.to == 'south' and row.froms == 'central': 
        return ['background-color: #000000'] * len(row)
    
    elif row.to == 'central' and row.froms == 'chiangmai':
        return ['background-color: #6F0000'] * len(row)

    else:
        # Return an empty list for even rows (no styling)
        return [''] * len(row)

In [3]:
engine = create_engine(f"postgresql+psycopg2://{cn.user}:{cn.password}@{cn.localhost}/{cn.database}",echo=False)

In [4]:
booking = pd.read_sql("select * from booking", engine)
region = pd.read_sql("select * from region",engine)
trailer = pd.read_sql("select * from trailer",engine)
destination = pd.read_sql("select * from destination",engine)
province = pd.read_sql("select * from province_entity",engine)
detail = pd.read_sql("select * from detail",engine).rename(columns={"id": "detail_id"})
user = pd.read_sql("select * from users",engine)
vehicle = pd.read_sql("select * from vehicle",engine)
current_date = datetime.now().date()

In [5]:
merged_df = booking.merge(region, left_on='fromId', right_on='id').merge(region, left_on='toId', right_on="id").drop(['id_y','id','fromId','toId'],axis=1).merge(trailer, left_on="trailerId", right_on="id").drop(['createDate_y','actExpire','id','trailerId'],axis=1).rename(columns={"region_x": "from","region_y": "to", "createDate_x": "createDate","registration":"trailer_registration"})

In [6]:
merged_df.createDate = merged_df.createDate.dt.date
merged_df.departureDate = merged_df.departureDate.dt.date
merged_df.arriveDate = merged_df.arriveDate.dt.date

In [7]:
merged_df = merged_df.astype({"createDate": "datetime64[ns]", 
                              "departureDate": "datetime64[ns]",
                              "arriveDate": "datetime64[ns]",
                              "status":"category",
                              "capacity":"Int8",
                              "from": "category",
                              "to":"category",
                              "deposit": "Int16",
                              "trailer_registration": "category"
                              }).rename(columns={"id_x": "booking_id"})

In [8]:

get_route  = (destination.merge(booking,left_on='booking', right_on="id").merge(province, left_on="province", right_on='id')).reset_index().groupby('booking').apply(lambda x: ','.join(x.province_y)).reset_index().rename(columns={0: 'route'});

C:\Users\User\AppData\Local\Temp\ipykernel_32352\731876730.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  get_route  = (destination.merge(booking,left_on='booking', right_on="id").merge(province, left_on="province", right_on='id')).reset_index().groupby('booking').apply(lambda x: ','.join(x.province_y)).reset_index().rename(columns={0: 'route'});

In [9]:
merged_df = merged_df.merge(get_route, left_on="booking_id", right_on='booking').sort_values('departureDate',ascending=False).drop(columns=["createDate"],axis=1)

In [10]:

detail = detail.merge(merged_df, left_on="bookingId", right_on="booking_id").drop(columns=['bookingId','deposit','booking']).merge(vehicle, left_on="vehicleId", right_on="id").drop(columns=["ownerId",'id',"vehicleId",'booking_id']).merge(
    user,left_on='userId', right_on="id").drop(columns=['createDate','age','userId','id']).merge(province,left_on="pickId",right_on="id").drop(columns=['id']).rename(columns={"province": "pick"}).merge(province, left_on="dropId",right_on='id').drop(columns=['id','pickId','dropId','capacity']).rename(columns={"province":"drop"})

In [11]:
details = detail.rename(columns={"from": "froms"}).sort_values('departureDate', ascending=False).drop(columns=["arriveDate","route",'sex']).query('status == "pending"').rename(columns={"tel":"Number"})
# detail

In [12]:
bookings  = merged_df.query("status =='pending' | status =='depart'").sort_values(["departureDate"], ascending=True).assign(isChiangmai = lambda x: x.route.str.contains('chiangmai')).drop(columns=['booking'])

In [13]:
north = bookings.query("route.str.contains('chiangrai|chiangmai', regex=True,case=False)").sort_values(['departureDate'], ascending=True).set_index("booking_id").drop(columns=['route'])
north.departureDate = north.departureDate.dt.strftime('%d-%m-%Y')
north.arriveDate = north.arriveDate.dt.strftime('%d-%m-%Y')
isan = bookings.query('trailer_registration ==  "outsource_ta"').drop(columns=['isChiangmai','route']).set_index('booking_id')

# chiangmai = north.query('trailer_registration == "outsource_petch"')

# chiangrai = north.query('trailer_registration == "outsource_one"')

In [14]:
isan.departureDate = isan.departureDate.dt.date
isan.arriveDate = isan.arriveDate.dt.date
isan.style.apply(highlight_odd_rows,axis=1)

In [15]:
north.style.apply(highlight_odd_rows,axis=1)

In [16]:
south = bookings.query("route.str.contains('hatyai|phuket', regex=True,case=False)").sort_values(['departureDate']).drop(columns=['isChiangmai','route']).set_index("booking_id")
south.departureDate = south.departureDate.dt.strftime('%d-%m-%Y')
south.arriveDate = south.arriveDate.dt.strftime('%d-%m-%Y')
south.style.apply(highlight_odd_rows,axis=1)

In [17]:
pending = details.drop(columns=['createDate_x','createDate_y']).set_index('detail_id').sort_values(['departureDate',"trailer_registration","drop"])
pending.departureDate = pending.departureDate.dt.strftime('%d-%m-%Y')

pending = pending.reindex(columns=['departureDate',"pick",'drop','name','lastName','Number','brand','model','registration','froms','to','trailer_registration','remark'])
pending.style.apply(highlight_rows, axis=1)

In [18]:
depart = detail.drop(columns=['createDate_x','route','createDate_y','sex']).query('departureDate.dt.date <= @current_date and status == "depart"').set_index('detail_id').sort_values('pick')
depart.departureDate = depart.departureDate.dt.date
depart.reindex(columns=['departureDate',"pick",'drop','name','lastName','tel','brand','registration','model','from','to','trailer_registration','remark']).style

In [19]:
south_date = current_date - pd.Timedelta(days=1)
arrived = detail.query('status == "arrived" & arriveDate.dt.date == @current_date and  arriveDate.dt.date >= @south_date' ).drop(columns=['route','sex','createDate_x','createDate_y']).set_index('detail_id')
arrived.departureDate = arrived.departureDate.dt.date
arrived.reindex(columns=['departureDate',"pick",'drop','name','lastName','tel','brand','registration','model','from','to','trailer_registration','remark']).sort_values(['to','drop']).style

In [20]:
today_booking = details.drop(columns=['createDate_y']).set_index('detail_id').rename(columns={"createDate_x": "createDate"}).query('createDate.dt.date == @current_date')
today_booking.reindex(columns=['departureDate',"pick",'drop','name','lastName','Number','brand','registration','model','froms','to','trailer_registration','remark'])

Empty DataFrame
Columns: [departureDate, pick, drop, name, lastName, Number, brand, registration, model, froms, to, trailer_registration, remark]
Index: []

In [21]:
user.set_index('id').sort_index().drop(columns=['createDate']).tail()
# # user.query('tel == "0849309353"')
# user.query('name == "บุญฑริก"').set_index('id')

           name     lastName         tel     sex  age
id
137     สายัณห์     ศิริบุตร  0801411982    male   65
138  วรรณ์เฉลิม   ช่วยประคอง  0909959987    male   40
139   ต่อศักดิ์    กั่วพานิช  0897293169    male   42
140     ธนวินท์     ศิริรจน์  0842895987    male   34
141   สันต์ณิศา  สันติปิยกุล  0614782644  female   35

In [22]:
user_car =vehicle.merge(user, left_on="ownerId", right_on="id").set_index('id_x').drop( columns=['createDate_x','createDate_y','id_y','sex','age','ownerId','tel']).sort_index()
user_car.tail()
# user_car.query('registration == "วฮ4313"')

       brand registration  model        name     lastName
id_x
117   toyota       ขต1398  yaris  วรรณ์เฉลิม   ช่วยประคอง
118   toyota       กย2033  altis   ต่อศักดิ์    กั่วพานิช
119     benz         งพ82      E     ธนวินท์     ศิริรจน์
120    honda        อ6856    hrv   สันต์ณิศา  สันติปิยกุล
121    mazda      6กล4640    cx3       owner        owner

In [23]:
# chiangmai = detail.query("route.str.contains('chiangrai|chiangmai', regex=True,case=False)").assign(isChiangmai = lambda x: x.route.str.contains('chiangmai'))
# chiangmai.groupby(["isChiangmai", pd.Grouper(key='departureDate', freq='W-SUN')]).count()

In [24]:
# test = detail.groupby(['from', pd.Grouper(key='departureDate', freq='W-MON'),'to']).count()

# pending[(pending['departureDate'] == '2025-09-28 00:00:00') & (pending['brand'] == 'mini')].count()

In [25]:
# detail.query(f"status == 'depart' and departureDate.dt.date == @current_date").reset_index().drop(["index"],axis=1)
# weekly report
# detail.loc[:, ['createDate_x','departureDate','arriveDate',"from","to",'pick','drop']].groupby(['from','to']).resample('W-Mon',on="createDate_x").count()

In [26]:
# user.sex.value_counts().plot.pie(y='sex',startangle=90)

In [27]:
# user.query('age > 18').age.value_counts().sort_index().plot.bar(color="green",title ="age")

In [28]:
# booking.drop(columns=['createDate']).sort_values('departureDate')

# detail.drop(columns=['remark', 'createDate_x', 'arriveDate','trailer_registration','route','createDate_y','from','to','registration','name','lastName','tel','departureDate','detail_id','status']).groupby(['pick','drop']).count()

In [29]:
# with pd.ExcelWriter('booking.xlsx', engine='xlsxwriter',datetime_format='yyyy-mm-dd') as writer:
#     chiangmai.to_excel(writer, sheet_name="chiangmai_booking",index=False, startrow=2)
#     chiangrai.to_excel(writer, sheet_name="chiangrai_booking", index=False, startrow=2)
#     south.to_excel(writer,sheet_name="south_booking",index=False, startrow=2)
#     isan.to_excel(writer,sheet_name="isan_booking",index=False, startrow=2)
#     pending.to_excel(writer,sheet_name="detail_booking",index=False, startrow=2)
#     depart.to_excel(writer,sheet_name="depart_booking",index=False, startrow=2)
#     arrived.to_excel(writer,sheet_name="arrived_booking",index=False, startrow=2)
#     writer.sheets["chiangmai_booking"].autofit()
#     writer.sheets["chiangrai_booking"].autofit()
#     writer.sheets["isan_booking"].autofit()
#     writer.sheets['south_booking'].autofit()
#     writer.sheets['detail_booking'].autofit()
#     writer.sheets['depart_booking'].autofit()
#     writer.sheets['arrived_booking'].autofit()